---
AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Autoscaling group for opsworks

Parameters:

  Identifier:
    Type: String
    Default: 6connex
    Description: A name identifier for the resources

  BuildsBucket:
    Type: String
    Description: builds bucket

  ImageId:
    Type: String
    Description: Amazon Linux image id

  StackId:
    Type: String
    Description: Opswork stack id

  LayerId:
    Type: String
    Description: Opswork layer id

  InstanceProfile:
    Type: String
    Description: Instance Profile to attach to the EC2 opswork instances

  SecurityGroupsIds:
    Type: List<String>
    Description: Security Ids to attach to LaunchTemplate

  InstanceType:
    Type: String
    Default: t2.small
    Description: Instance type

  KeyName:
    Type: String
    Default: LuisKeyPair
    Description: Keypair for the instances

  SubnetsIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of avalability zones

  S3ConfigFiles:
    Type: String
    Description: S3 Bucket to download configuration files

  RabbitMqUser:
    Type: String
    Description: rabbit mq user

  RabbitMqPassword:
    Type: String
    NoEcho: true
    Description: rabbit mq password

  RabbitMqPort:
    Type: Number
    Default: 0
    Description: rabbit mq port to use

  ConfigurationType:
    Type: String
    Default: 'rts'
    Description: type of configuration for files
    AllowedValues:
    - rts
    - other

  OwnerName:
    Type: String
    Default: nclouds
    Description: An arbitrary tag name for the owner of these resources

  ProjectName:
    Type: String
    Default: 6connex
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags


Resources:

  RabbitMqCredentialsSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub rabbit mq credentials in env ${Environment}
      Name: !Sub ${Environment}/${Identifier}/RabbitMq/RabbitmqCredentials
      SecretString: !Sub '{"username":"${RabbitMqUser}","password":"${RabbitMqPassword}"}'
      Tags:
      - Key: Name
        Value: !Sub ${Identifier}-${Environment}-rabbitmq-credentials
      - Key: Owner
        Value: !Ref OwnerName
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

  MetricsInstance:
    Type: AWS::EC2::Instance
    DependsOn:
    - RabbitMqCredentialsSecrets
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      SecurityGroupIds: !Ref SecurityGroupsIds
      SubnetId: !Select [ 1, !Ref SubnetsIds ]
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sed -i'' -e 's/.*requiretty.*//' /etc/sudoers
            #pip install --upgrade awscli

            echo "ssm agent"
            sudo start amazon-ssm-agent

            # installing jq
            sudo yum install -y jq

            # updating aws cli
            sudo yum update -y aws-cli

            # python3
            yum install python36 -y
            curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python3 get-pip.py
            /usr/local/bin/pip3 install jenkinsapi

            INSTANCE_ID=$(aws opsworks register --use-instance-profile --infrastructure-class ec2 --region us-east-1 --stack-id ${StackId} --override-hostname ${Identifier}-${Environment}-metrics --local 2>&1 |grep -o 'Instance ID: .*' |cut -d' ' -f3)
            /usr/bin/aws opsworks wait instance-registered --region us-east-1 --instance-id $INSTANCE_ID
            /usr/bin/aws opsworks assign-instance --region us-east-1 --instance-id $INSTANCE_ID --layer-ids ${LayerId}
            /usr/bin/aws configure set default.region ${AWS::Region}

            sleep 2m

            # grabbing the files from s3 to set jenkins trigger
            echo "configuration files"
            sudo /usr/bin/aws s3 sync s3://${S3ConfigFiles}/${Environment}/configuration_files /tmp/configuration
            cd /tmp/configuration

            # executing jenkins job
            # build parameters
            echo BUILD_NUMBER=$(/usr/bin/aws ssm get-parameters --region ${AWS::Region} --names "/${Environment}/${Identifier}/Builds/BuildNumber" | jq ".Parameters" | jq ".[] .Value") >> jenkins_params.py
            echo JENKINS_USER=$(/usr/bin/aws ssm get-parameters --region ${AWS::Region} --names "/jenkins/username" | jq ".Parameters" | jq ".[] .Value") >> jenkins_params.py
            echo JENKINS_PASS=$(/usr/bin/aws ssm get-parameters --region ${AWS::Region} --names "/jenkins/password" | jq ".Parameters" | jq ".[] .Value") >> jenkins_params.py
            echo JENKINS_IP=$(/usr/bin/aws ssm get-parameters --region ${AWS::Region} --names "/jenkins/IpAddress" | jq ".Parameters" | jq ".[] .Value") >>  jenkins_params.py
            echo JENKINS_JOB=$(/usr/bin/aws ssm get-parameters --region ${AWS::Region} --names "/${Environment}/${Identifier}/Jenkins/MetricsJob" | jq ".Parameters" | jq ".[] .Value") >> jenkins_params.py
            echo ID_INSTANCE=\"$(curl  http://169.254.169.254/latest/meta-data/instance-id)\" >> jenkins_params.py
            
            echo "calling jenkins job"
            sudo python3 jenkins_tringger.py.template
            sudo rm -rf jenkins_params.py

      Tags:
      - Key: Name
        Value: !Sub ${Identifier}-${Environment}-metricsnode
      - Key: Owner
        Value: !Ref OwnerName
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

  RabbitHostParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitHost
      Type: String
      Value: !GetAtt MetricsInstance.PrivateIp
      Description: !Sub rabbit host on Environment ${Environment}
      Tags:
        Name: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitHost
        OwnerName: !Ref OwnerName
        ProjectName: !Ref ProjectName
        Environment: !Ref  Environment
  
  RabbitPortParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitPort
      Type: String
      Value: !Ref RabbitMqPort
      Description: !Sub rabbit port on Environment ${Environment}
      Tags:
        Name: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitPort
        OwnerName: !Ref OwnerName
        ProjectName: !Ref ProjectName
        Environment: !Ref  Environment
Outputs:

  MetricsNodeIp:
    Description: metrics node ip
    Value: !GetAtt MetricsInstance.PrivateIp

  MetricsNodeInstanceId:
    Description: metrics node instace id
    Value: !Ref MetricsInstance

  RabbitHostName:
    Description: rabbit host name
    Value: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitHost

  RabbitPortName:
    Description: rabbit port name
    Value: !Sub /${Environment}/${Identifier}/RabbitMq/RabbitPort
