---
AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Autoscaling group for opswork instances based on load.

Parameters:

  Identifier:
    Type: String
    Default: 6connex
    Description: A name identifier for the resources

  VpcId:
    Type: String
    Description: vpc id

  AlbArn:
    Type: String
    Description: Application Load balancer ARN

  AlbListenerArn:
    Type: String
    Description: Application load balancer listener

  MetricsNodeId:
    Type: String
    Default: ''
    Description: metrics node id

  RtsDomain:
    Type: String
    Description: rts domain name

  TomcatDomain:
    Type: String
    Description: tomcat domain name

  MetricDomain:
    Type: String
    Description: metrics domain name

  OwnerName:
    Type: String
    Default: nclouds
    Description: An arbitrary tag name for the owner of these resources

  ProjectName:
    Type: String
    Default: 6connex
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

Conditions:

  NoMetricsNode: !Equals [!Ref MetricsNodeId, '']
  CreateMetrics: !Not [Condition: NoMetricsNode]

Resources:

  RtsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${Identifier}-${Environment}-rts-tg
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: stickiness.enabled
        Value: true
      - Key: stickiness.lb_cookie.duration_seconds
        Value: '7200'
      Tags:
      - Key: Name
        Value: !Sub ${Identifier}-${Environment}-rts-target
      - Key: Owner
        Value: !Ref OwnerName
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

  RtsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref RtsTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref RtsDomain
      ListenerArn: !Ref AlbListenerArn
      Priority: 2

  TomcatTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${Identifier}-${Environment}-tomcat-tg
      Port: 443
      VpcId: !Ref VpcId
      Protocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      Tags:
      - Key: Name
        Value: !Sub ${Identifier}-${Environment}-tomcat-target
      - Key: Owner
        Value: !Ref OwnerName
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

  TomcatListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref TomcatTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref TomcatDomain
      ListenerArn: !Ref AlbListenerArn
      Priority: 3

  MetricsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: CreateMetrics
    Properties:
      Name: !Sub ${Identifier}-${Environment}-metrics-tg
      Port: 8080
      VpcId: !Ref VpcId
      Protocol: HTTP
      HealthCheckPath: /version.xml
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      Targets:
      - Id: !Ref MetricsNodeId
      Tags:
      - Key: Name
        Value: !Sub ${Identifier}-${Environment}-metrics-target
      - Key: Owner
        Value: !Ref OwnerName
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment

  MetricsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: CreateMetrics
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref MetricsTargetGroup
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Ref MetricDomain
      ListenerArn: !Ref AlbListenerArn
      Priority: 4

Outputs:
  RtsTg:
    Description: target group for rts
    Value: !Ref RtsTargetGroup

  RtsFullName:
    Description: rts full name
    Value: !GetAtt RtsTargetGroup.TargetGroupFullName

  TomcatTg:
    Description: tomcat target group
    Value: !Ref TomcatTargetGroup

  TomcatFullName:
    Description: tomcat full name
    Value: !GetAtt TomcatTargetGroup.TargetGroupFullName
